server:
  port: 7888

spring:
  application:
    name: config-center-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/config_center?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC

  sql:
    init:
      mode: always
      schema-locations: classpath:db/init-schema.sql

mybatis:
  config-location: classpath:mybatis-config.xml
