### list
GET http://localhost:7888/configs/list?app=zst&namespace=default&environment=default

### edit
POST http://localhost:7888/configs/edit
Content-Type: application/json

{
  "app": "zst",
  "namespace": "default",
  "environment": "default",
  "configs": {
    "zst.aa": "a02",
    "zst.bb": "b02",
    "zst.cc": "c02"
  }
}

### delete
DELETE http://localhost:7888/configs/delete?app=zst&namespace=default&environment=default&key=key1&key=ha

### version
GET http://localhost:7888/version/getVersion?app=zst&namespace=default&environment=default&clientVersion=0