### list
GET http://localhost:7888/configs/list?app=rpc-01&namespace=default&environment=default

### edit
POST http://localhost:7888/configs/edit
Content-Type: application/json

{
  "app": "rpc-01",
  "namespace": "default",
  "environment": "default",
  "configs": {
    "rpc.registry.instance-id": "provider1",
    "rpc.registry.instance-ip": "127.0.0.1",
    "rpc.filter.cache.enable": false,
    "registry.customrc.addresses": "http://192.168.123.249:8444,http://192.168.123.249:8445"
  }
}

### delete
DELETE http://localhost:7888/configs/delete?app=zst&namespace=default&environment=default&key=key1&key=ha

### version
GET http://localhost:7888/version/getVersion?app=zst&namespace=default&environment=default&clientVersion=8